spring:
  application:
    name: offering-server
  datasource:
    url: jdbc:mysql://localhost:3366/offeringdb
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true