spring:
  application:
    name: offering
  datasource:
    url: jdbc:mysql://localhost:3366/offeringdb
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
    properties:
      hibernate:
        format_sql: true

